### ISSUE TITLE
Compling comments in a weird way

### ISSUE THREAD

**Issue by CeriW** [babobski/Komodo-sass-compiler#7]
Hiya,

I've got a strange issue when compiling my SCSS - it's rearranging the comments into strange places.

I've attached two screenshots to get across what I mean. One shows the uncompiled SCSS, which has the comments in logical places. The other shows the compiled CSS, which has rearranged all the comments to the top.

![screen shot 2016-12-12 at 11 03 38](https://cloud.githubusercontent.com/assets/18597781/21097292/c5413d44-c05b-11e6-997a-577b544389cd.png)

![screen shot 2016-12-12 at 11 05 41](https://cloud.githubusercontent.com/assets/18597781/21097297/c8dce3d6-c05b-11e6-9eff-de77ded79319.png)

It only seems to occur when I nest this code inside something else, as can be seen here nested inside the breakpoint code.

Is there anything that can be done to prevent this from happening?

**Comment by babobski** [comment]
@CeriW tried to reproduce but am unable to.

Tried to compile this but it is working for me:
```scss

body {
	height: 100%;
	text-align: center;
}

/* test comment */
.color {
	color: #333;
	background: #333;
}

$breakpointl: unquote('>=1');

@breakpoint #{$breakpointl} {
	/* test comment 2 */
	.div {
		display: block;
		/* test comment inside */
		.test {
			color: #222;
		}
		.test {
			/*---- a deeper nested comment ----*/
			.test {
				color: #444;
				&:hover, &:active {
					color: #222;
					/* before comment */
					&:before {
						content:  '';
					}
				}
			}
		}
	}
}

``` 

Can you maybe supply a sample code where the issue is appearing?

A other thing I can do is to add a options to remove all comments, as I think comments should not be in the output file ( because the css file is intended only for the browser and the scss for the developer ).

Or do you need the  comments in you're css?
